//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSPruebasNube.equiposWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Equipo", Namespace="http://schemas.datacontract.org/2004/07/PrestamosServicios.Dominio")]
    [System.SerializableAttribute()]
    public partial class Equipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((this.ModeloField.Equals(value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serie {
            get {
                return this.SerieField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieField, value) != true)) {
                    this.SerieField = value;
                    this.RaisePropertyChanged("Serie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExcepcionEquipo", Namespace="http://schemas.datacontract.org/2004/07/PrestamosServicios.Dominio")]
    [System.SerializableAttribute()]
    public partial class ExcepcionEquipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod {
            get {
                return this.CodField;
            }
            set {
                if ((object.ReferenceEquals(this.CodField, value) != true)) {
                    this.CodField = value;
                    this.RaisePropertyChanged("Cod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="equiposWS.IEquipos")]
    public interface IEquipos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/CrearEquipo", ReplyAction="http://tempuri.org/IEquipos/CrearEquipoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DMSPruebasNube.equiposWS.ExcepcionEquipo), Action="http://tempuri.org/IEquipos/CrearEquipoExcepcionEquipoFault", Name="ExcepcionEquipo", Namespace="http://schemas.datacontract.org/2004/07/PrestamosServicios.Dominio")]
        DMSPruebasNube.equiposWS.Equipo CrearEquipo(int modelo, string estado, string serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/CrearEquipo", ReplyAction="http://tempuri.org/IEquipos/CrearEquipoResponse")]
        System.Threading.Tasks.Task<DMSPruebasNube.equiposWS.Equipo> CrearEquipoAsync(int modelo, string estado, string serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ObtenerEquipo", ReplyAction="http://tempuri.org/IEquipos/ObtenerEquipoResponse")]
        DMSPruebasNube.equiposWS.Equipo ObtenerEquipo(string serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ObtenerEquipo", ReplyAction="http://tempuri.org/IEquipos/ObtenerEquipoResponse")]
        System.Threading.Tasks.Task<DMSPruebasNube.equiposWS.Equipo> ObtenerEquipoAsync(string serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ModificarEquipo", ReplyAction="http://tempuri.org/IEquipos/ModificarEquipoResponse")]
        DMSPruebasNube.equiposWS.Equipo ModificarEquipo(int modelo, string estado, string serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ModificarEquipo", ReplyAction="http://tempuri.org/IEquipos/ModificarEquipoResponse")]
        System.Threading.Tasks.Task<DMSPruebasNube.equiposWS.Equipo> ModificarEquipoAsync(int modelo, string estado, string serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/EliminarEquipo", ReplyAction="http://tempuri.org/IEquipos/EliminarEquipoResponse")]
        void EliminarEquipo(string serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/EliminarEquipo", ReplyAction="http://tempuri.org/IEquipos/EliminarEquipoResponse")]
        System.Threading.Tasks.Task EliminarEquipoAsync(string serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ListarEquipos", ReplyAction="http://tempuri.org/IEquipos/ListarEquiposResponse")]
        DMSPruebasNube.equiposWS.Equipo[] ListarEquipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ListarEquipos", ReplyAction="http://tempuri.org/IEquipos/ListarEquiposResponse")]
        System.Threading.Tasks.Task<DMSPruebasNube.equiposWS.Equipo[]> ListarEquiposAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEquiposChannel : DMSPruebasNube.equiposWS.IEquipos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EquiposClient : System.ServiceModel.ClientBase<DMSPruebasNube.equiposWS.IEquipos>, DMSPruebasNube.equiposWS.IEquipos {
        
        public EquiposClient() {
        }
        
        public EquiposClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EquiposClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquiposClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquiposClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DMSPruebasNube.equiposWS.Equipo CrearEquipo(int modelo, string estado, string serie) {
            return base.Channel.CrearEquipo(modelo, estado, serie);
        }
        
        public System.Threading.Tasks.Task<DMSPruebasNube.equiposWS.Equipo> CrearEquipoAsync(int modelo, string estado, string serie) {
            return base.Channel.CrearEquipoAsync(modelo, estado, serie);
        }
        
        public DMSPruebasNube.equiposWS.Equipo ObtenerEquipo(string serie) {
            return base.Channel.ObtenerEquipo(serie);
        }
        
        public System.Threading.Tasks.Task<DMSPruebasNube.equiposWS.Equipo> ObtenerEquipoAsync(string serie) {
            return base.Channel.ObtenerEquipoAsync(serie);
        }
        
        public DMSPruebasNube.equiposWS.Equipo ModificarEquipo(int modelo, string estado, string serie) {
            return base.Channel.ModificarEquipo(modelo, estado, serie);
        }
        
        public System.Threading.Tasks.Task<DMSPruebasNube.equiposWS.Equipo> ModificarEquipoAsync(int modelo, string estado, string serie) {
            return base.Channel.ModificarEquipoAsync(modelo, estado, serie);
        }
        
        public void EliminarEquipo(string serie) {
            base.Channel.EliminarEquipo(serie);
        }
        
        public System.Threading.Tasks.Task EliminarEquipoAsync(string serie) {
            return base.Channel.EliminarEquipoAsync(serie);
        }
        
        public DMSPruebasNube.equiposWS.Equipo[] ListarEquipos() {
            return base.Channel.ListarEquipos();
        }
        
        public System.Threading.Tasks.Task<DMSPruebasNube.equiposWS.Equipo[]> ListarEquiposAsync() {
            return base.Channel.ListarEquiposAsync();
        }
    }
}
