//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestamosServicios.equipoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Equipo", Namespace="http://schemas.datacontract.org/2004/07/PrestamosServicios.Dominio")]
    [System.SerializableAttribute()]
    public partial class Equipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serie {
            get {
                return this.SerieField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieField, value) != true)) {
                    this.SerieField = value;
                    this.RaisePropertyChanged("Serie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquipoRepetidoExcepcion", Namespace="http://schemas.datacontract.org/2004/07/PrestamosServicios.Dominio")]
    [System.SerializableAttribute()]
    public partial class EquipoRepetidoExcepcion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquipoEliminarExcepcion", Namespace="http://schemas.datacontract.org/2004/07/PrestamosServicios.Dominio")]
    [System.SerializableAttribute()]
    public partial class EquipoEliminarExcepcion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="equipoWS.IEquipos")]
    public interface IEquipos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/CrearEquipo", ReplyAction="http://tempuri.org/IEquipos/CrearEquipoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PrestamosServicios.equipoWS.EquipoRepetidoExcepcion), Action="http://tempuri.org/IEquipos/CrearEquipoEquipoRepetidoExcepcionFault", Name="EquipoRepetidoExcepcion", Namespace="http://schemas.datacontract.org/2004/07/PrestamosServicios.Dominio")]
        PrestamosServicios.equipoWS.Equipo CrearEquipo(string serie, string modelo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/CrearEquipo", ReplyAction="http://tempuri.org/IEquipos/CrearEquipoResponse")]
        System.Threading.Tasks.Task<PrestamosServicios.equipoWS.Equipo> CrearEquipoAsync(string serie, string modelo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ObtenerEquipo", ReplyAction="http://tempuri.org/IEquipos/ObtenerEquipoResponse")]
        PrestamosServicios.equipoWS.Equipo ObtenerEquipo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ObtenerEquipo", ReplyAction="http://tempuri.org/IEquipos/ObtenerEquipoResponse")]
        System.Threading.Tasks.Task<PrestamosServicios.equipoWS.Equipo> ObtenerEquipoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ModificarEquipo", ReplyAction="http://tempuri.org/IEquipos/ModificarEquipoResponse")]
        PrestamosServicios.equipoWS.Equipo ModificarEquipo(int id, string serie, string modelo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ModificarEquipo", ReplyAction="http://tempuri.org/IEquipos/ModificarEquipoResponse")]
        System.Threading.Tasks.Task<PrestamosServicios.equipoWS.Equipo> ModificarEquipoAsync(int id, string serie, string modelo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/EliminarEquipo", ReplyAction="http://tempuri.org/IEquipos/EliminarEquipoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PrestamosServicios.equipoWS.EquipoEliminarExcepcion), Action="http://tempuri.org/IEquipos/EliminarEquipoEquipoEliminarExcepcionFault", Name="EquipoEliminarExcepcion", Namespace="http://schemas.datacontract.org/2004/07/PrestamosServicios.Dominio")]
        void EliminarEquipo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/EliminarEquipo", ReplyAction="http://tempuri.org/IEquipos/EliminarEquipoResponse")]
        System.Threading.Tasks.Task EliminarEquipoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ListarEquipos", ReplyAction="http://tempuri.org/IEquipos/ListarEquiposResponse")]
        PrestamosServicios.equipoWS.Equipo[] ListarEquipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ListarEquipos", ReplyAction="http://tempuri.org/IEquipos/ListarEquiposResponse")]
        System.Threading.Tasks.Task<PrestamosServicios.equipoWS.Equipo[]> ListarEquiposAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ListarDisponiblesModelo", ReplyAction="http://tempuri.org/IEquipos/ListarDisponiblesModeloResponse")]
        PrestamosServicios.equipoWS.Equipo[] ListarDisponiblesModelo(string modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ListarDisponiblesModelo", ReplyAction="http://tempuri.org/IEquipos/ListarDisponiblesModeloResponse")]
        System.Threading.Tasks.Task<PrestamosServicios.equipoWS.Equipo[]> ListarDisponiblesModeloAsync(string modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ObtenerSerie", ReplyAction="http://tempuri.org/IEquipos/ObtenerSerieResponse")]
        PrestamosServicios.equipoWS.Equipo ObtenerSerie(string serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ObtenerSerie", ReplyAction="http://tempuri.org/IEquipos/ObtenerSerieResponse")]
        System.Threading.Tasks.Task<PrestamosServicios.equipoWS.Equipo> ObtenerSerieAsync(string serie);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEquiposChannel : PrestamosServicios.equipoWS.IEquipos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EquiposClient : System.ServiceModel.ClientBase<PrestamosServicios.equipoWS.IEquipos>, PrestamosServicios.equipoWS.IEquipos {
        
        public EquiposClient() {
        }
        
        public EquiposClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EquiposClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquiposClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquiposClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PrestamosServicios.equipoWS.Equipo CrearEquipo(string serie, string modelo, string estado) {
            return base.Channel.CrearEquipo(serie, modelo, estado);
        }
        
        public System.Threading.Tasks.Task<PrestamosServicios.equipoWS.Equipo> CrearEquipoAsync(string serie, string modelo, string estado) {
            return base.Channel.CrearEquipoAsync(serie, modelo, estado);
        }
        
        public PrestamosServicios.equipoWS.Equipo ObtenerEquipo(int id) {
            return base.Channel.ObtenerEquipo(id);
        }
        
        public System.Threading.Tasks.Task<PrestamosServicios.equipoWS.Equipo> ObtenerEquipoAsync(int id) {
            return base.Channel.ObtenerEquipoAsync(id);
        }
        
        public PrestamosServicios.equipoWS.Equipo ModificarEquipo(int id, string serie, string modelo, string estado) {
            return base.Channel.ModificarEquipo(id, serie, modelo, estado);
        }
        
        public System.Threading.Tasks.Task<PrestamosServicios.equipoWS.Equipo> ModificarEquipoAsync(int id, string serie, string modelo, string estado) {
            return base.Channel.ModificarEquipoAsync(id, serie, modelo, estado);
        }
        
        public void EliminarEquipo(int id) {
            base.Channel.EliminarEquipo(id);
        }
        
        public System.Threading.Tasks.Task EliminarEquipoAsync(int id) {
            return base.Channel.EliminarEquipoAsync(id);
        }
        
        public PrestamosServicios.equipoWS.Equipo[] ListarEquipos() {
            return base.Channel.ListarEquipos();
        }
        
        public System.Threading.Tasks.Task<PrestamosServicios.equipoWS.Equipo[]> ListarEquiposAsync() {
            return base.Channel.ListarEquiposAsync();
        }
        
        public PrestamosServicios.equipoWS.Equipo[] ListarDisponiblesModelo(string modelo) {
            return base.Channel.ListarDisponiblesModelo(modelo);
        }
        
        public System.Threading.Tasks.Task<PrestamosServicios.equipoWS.Equipo[]> ListarDisponiblesModeloAsync(string modelo) {
            return base.Channel.ListarDisponiblesModeloAsync(modelo);
        }
        
        public PrestamosServicios.equipoWS.Equipo ObtenerSerie(string serie) {
            return base.Channel.ObtenerSerie(serie);
        }
        
        public System.Threading.Tasks.Task<PrestamosServicios.equipoWS.Equipo> ObtenerSerieAsync(string serie) {
            return base.Channel.ObtenerSerieAsync(serie);
        }
    }
}
